### PR TITLE
fix: dynamic origin handling and updated redirect URLs for environmen…

### LINKED ISSUE #385: Bug incorrect Reset Password URLs in a deployed environment
### Description of the Bug

When the User is redirected to the reset password link (e.g., http://localhost:3000/login/reset-password?message=Unable%20to%20reset%20Password.%20Try%20again!) on the deployed version, the URL defaults to http://localhost:3000. However, it should point to the actual URL of theImage
 website.

### What should happen instead

Instead of defaulting to http://localhost:3000, the reset password link should dynamically generate the correct URL based on the environment.
In the deployed version, the link should point to the actual domain of the website (e.g., https://your-deployed-domain.com/login/reset-password) instead of the localhost URL.

### Steps to reproduce this bug

1. Open the **deployed** website.
2. Click on the Forgot Password link on the login page.
3. Enter your email address in the provided field.
4. Click the Confirm Reset button.
5. Check your email inbox for a "Reset Your Password" email.
6. In the email, click on the Reset Password link.
7. Observed Result: The reset password link redirects to http://localhost:3000 instead of the deployed domain.

### What could we do to solve this bug?

Consider updating the part of the code with the revised logic to better handle different environments:
```
let origin = headers().get('origin');
if (!origin) {
  origin = process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000/';
}
```

### Assignment

This issue is free for anyone to take

### PR DESCRIPTION
**Pull request by OlenaReukova**
# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review on my code
- [ ] I have made corresponding changes to the documentation (if any were needed)
- [x] My changes generate no new warnings or errors
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and previously existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# Description

**Relates #385 <u>OR</u> Closes #385 **  

Instead of defaulting to http://localhost:3000/, the **reset password email link** should dynamically generate the correct URL based on the environment.

In the deployed version, **the reset password email link** should point to the actual domain of the website (e.g., https://your-deployed-domain.com/login/reset-password) instead of the localhost URL.

**Code Update:**

- Refactored origin detection to handle cases where the value is missing or undefined smoothly.
- Default to http://localhost:3000 for development mode.
- Dynamically set the origin for production using NEXT_PUBLIC_SITE_URL environment variable.

```
const headersList = await headers();
  let origin: string | null = headersList.get('origin') || null;

  if (!origin) {
    origin =
      process.env.NODE_ENV === 'development'
        ? 'http://localhost:3000'
        : process.env.NEXT_PUBLIC_SITE_URL || null;
  }
```
**Configuration Update:**

Updated **config.toml** to include additional production redirect URLs `"https://**cool-creponne-3e1272.netlify.app/**", "https://cool-creponne-3e1272.netlify.app/login/reset-password"` to ensure Supabase accepts them, preventing failed password reset flows due to unlisted URLs.

[(Supabase Docs)](https://supabase.com/docs/guides/auth/redirect-urls)

### Files changed

- app/(auth)/login/forgot-password/page.tsx
- config.toml

### UI changes

no UI changes

### Changes to Documentation

No changes needed.

# Tests

All previous tests passed during local development.

### CODE REVIEW

File: app/(auth)/login/forgot-password/page.tsx [hunk 1]
```diff
@@ -10,9 +10,14 @@ export default async function ForgotPassword({
...
-  let origin = headers().get('origin');
+  const headersList = await headers();
+  let origin: string | null = headersList.get('origin') || null;
+
   if (!origin) {
-    origin = 'http://localhost:3000/';
+    origin =
+      process.env.NODE_ENV === 'development'
+        ? 'http://localhost:3000'
+        : process.env.NEXT_PUBLIC_SITE_URL || null;
```
Comment (camelPhonso) [inline app/(auth)/login/forgot-password/page.tsx]: I'm not entirely sure we need to have this `if` statement at all but definitely we don't want to evaluate to `process.env.NEXT_PUBLIC_SITE_URL` or `null` - we want to get rid of any possible `null`s here so we don't send people to a 404

File: supabase/config.toml [hunk 2]
```diff
@@ -76,7 +76,7 @@ enabled = true
 # in emails.
 site_url = "http://localhost:3000"
 # A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
-additional_redirect_urls = ["http://localhost:3000/login/reset-password", "http://localhost:3000/**"]
+additional_redirect_urls = ["http://localhost:3000/login/reset-password", "http://localhost:3000/**", "https://**cool-creponne-3e1272.netlify.app/**", "https://cool-creponne-3e1272.netlify.app/login/reset-password"]
```
Comment (camelPhonso) [inline supabase/config.toml]: no I don't think we want this here. This field is for `additional` urls because the base url is configured on the production project in supabase to be kept out of the development environment

**Review by camelPhonso — COMMENTED** [review]
I have a theory that this needs to be sorted with some tweaks in supabase but I no longer have access because I'm not logged in with my old email account. Can someone reach out on discord and give me access on my personal email?

File: supabase/config.toml (hunk 2 above)
Comment (OlenaReukova) [reply supabase/config.toml]: I cancelled the changes.

**Comment by OlenaReukova** [comment]
The console.log("Origin", origin) confirms that the origin value is fetched correctly during my tests, and no errors (e.g., null or unexpected results) occur. This makes me believe that the production deployment should work as expected, provided the server environment properly sets the origin header.

**Review by camelPhonso — APPROVED** [review]
Sorry for the wait Olena. Thanks for reviewing the origin set up and following up in the comments.

This seems grand 👌 ✨
