### PR TITLE
#256/browse items

### LINKED ISSUE #302: `ItemCard` is declaring "Postage Covered" in wrong scenario
### Description of the Bug

When a user  uploads an item to the database it's displayed on Kindly with a label saying that Postage is covered if the item has value `TRUE` for the property `postable`.

This value is passed to the `ItemCard` on `DonatedItemsList.tsx`

### What should happen instead

The label of "postage covered" should be conditional on the value of the property `postage_covered` instead.

### Steps to reproduce this bug

1. Log in with the test donor account provided in `BEFORE_YOUR_FIRST_ISSUE.md`
2. Visit your profile page and edit one of your items
3. Tick 'Willing to Post' but not 'Postage Covered' 
4. View your list of donated items again - the item you edited says "postage covered"

Image

Image

### What could we do to solve this bug?

We can simply replace `item.postable` with `item.postage_covered` when mapping through the list of donated items in `DonatedItemsList.tsx`

This might also need to be done in other parts of the code like `search/[results]/page.tsx`

### Assignment

This issue is free for anyone to take

### PR DESCRIPTION
**Pull request by nichgalzin**
# Description
**Relates #256**  
**Relates #257**  
**Closes #302**

This PR updates the search and filter functionality of the /search route. It updates the search bar and filter components and has removed the search-results as it in now handled as a front end task in the main search page.

Highlights:
 - Updates the state of all search related params to a single state object called search params
 - Controls the viewing of search results on the search Page.tsx route in the new created temsDisplayContainer component. 
 - Have refactored the filter functions to the self contained FilterOptions component, with all components within refactored to optimise testing (to be completed in a follow up PR)
 - Refactored the searchItems supabase model to allow for more nuanced searching. As well have condensed the logic of which query, category and subcategory values are present into a single model.
- Have put in place a cursor value in the current search model to allow for results pagination in a future issue.

### Files changed

Include one to two lines on the necessary changes to each file.

### UI changes

Screenshot 2024-07-26 at 12 24 51

Screenshot 2024-07-26 at 12 25 21

# Tests

Tests will be submitted for this issue in a follow up PR

### CODE REVIEW

File: supabase/models/filtering-items/searchItems.ts [hunk 1]
```diff
@@ -0,0 +1,62 @@
...
+  searchParams: SearchParamsType
+): Promise<PartialItem[]> {
+  const { query, category, subcategory, limit, cursor } = searchParams;
+  const supabase = newClient();
+
+  try {
+    let queryBuilder = supabase.from('items').select();
+
+    switch (true) {
+      case query && !!category && !!subcategory:
```
Comment (camelPhonso) [inline supabase/models/filtering-items/searchItems.ts:15]: I think we went over this syntax before but I'm struggling a little.

I suppose it's checking if cases evaluate to `true`, which feels weird but I can see how it fits our needs here. But why are we double-negating if just say `category &&` will evaluate it to a truthy if there is a value to the variable?

**Review by camelPhonso — CHANGES_REQUESTED** [review]
Left a few questions/suggestions - what you've walked me through before is all looking good though.

There's also a build fail and these changes broke one of the E2E tests 😬

File: cypress/support/page_objects/searchPage.js [hunk 2]
```diff
@@ -1,13 +1,17 @@
...
-  seeResultsButton() {
-    return cy.get('button').contains('SEE RESULTS').should('be.visible');
-  }
+  // toysButton() {
+  //   return cy.get('button').contains('Toys').should('be.visible');
+  // }
+
+  // seeResultsButton() {
+  //   return cy.get('button').contains('APPLY FILTERS').should('be.visible');
+  // }
```
Comment (camelPhonso) [inline cypress/support/page_objects/searchPage.js]: ghost_busters

**Review by camelPhonso — APPROVED** [review]
Thanks, good to go
