### PR TITLE
#255/no conversation starter for reserved items + reserved label

### LINKED ISSUE #255: Items that have been marked as 'Reserved' should not allow users to enquire about them 🙅
# Expected Behaviour

When an Item has been marked by the Donor as 'Reserved', refugee users should not be able to start new conversations from this Items card.

- [ ] The Item Page should show a notification that the Item is reserved
- [ ] The Item Page should not show the `NewConversationButton.tsx`

# Current Behaviour

The database schema already includes a value for reserved Items and the seed data includes Items that are marked as reserved but this is not noticeable on the front end.

## Steps to Reproduce
1. Visit the `Studio Url` link for your local database
2. Find an Item in the `items` table that has the `reserved` value set to `TRUE`
3. Log into Kindly and visit the Item page for that item (guarantee that you are logged in with a 'refugee' account)
4. The 'Message' button is visible to you

### PR DESCRIPTION
**Pull request by mickeymarse**
# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review on my code
- ~[ ] I have made corresponding changes to the documentation (if any were needed)~
- [x] My changes generate no new warnings or errors
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and previously existing unit tests pass locally with my changes
- ~[ ] Any dependent changes have been merged and published in downstream modules~

# Description

**Closes #255 **  
A **Reserved** tag has been added to `reserved` items.
I didn't consult anyone for the styling, but I'm happy to change it if needed. For now, is a pill using the `primaryOrange` color reading **Reserved**.

Moreover, `reserved` items now don't show a button to start a new conversation.

### Files changed

`app/(dashboard)/item/[id]/page.tsx`
- Added conditional for showing conversation button and reserved label
`components/ItemCard.tsx`
- Added conditional for showing reserved label
`app/(dashboard)/search/[results]/page.tsx`
- Imported the `reserved` prop during search
`components/ItemCard.stories.ts`
- Added reserved prop
`app/globals.css`
- Added a max width to `card` class to compensate for extra label

### UI changes

Screenshot_2024-07-12_11-03-47
Screenshot_2024-07-12_11-04-14

# Tests

I've updated the Storybook test for `ItemCard`.
However, I noticed that `npm run test` does not work. I believe because the project has moved away from Playwright, but the script hasn't been updated?

# Extra

Can't understand why the app doesn't show the images of the items (as well as the avatar) that I personally created and uploaded.
I get this error message in terminal:
` ⨯ upstream image response failed for https://undfcbmldjkujposixvn.supabase.co/storage/v1/object/public/images/5da54982
-81e8-475b-9707-8b39bbabca18/c72d9fd6-7de7-4deb-822b-067b962dc9fe 400`

### CODE REVIEW

File: app/(dashboard)/item/[id]/page.tsx [hunk 1]
```diff
@@ -53,7 +54,14 @@ const DisplayItemDetails = async ({ params }: { params: { id: string } }) => {
               postage_covered={item.postage_covered}
             />
             <div className='min-h-40 w-full bg-secondaryGray p-10 md:w-1/2 md:rounded-lg'>
-              <h2 className='text-xl italic'>{item.item_name}</h2>
+              <div className='flex flex-row content-start justify-between'>
+                <h2 className='text-xl italic'>{item.item_name}</h2>
+                {item.reserved && (
+                  <p className='-m-2 rounded-full bg-primaryOrange p-3'>
+                    Reserved
+                  </p>
```
Comment (camelPhonso) [inline app/(dashboard)/item/[id]/page.tsx:62]: Really simple solution 👌 

I know we don't have a design for this flag at the moment so there was no guidance in the issue but can you try to remove the background and just make the font this colour? Maybe make it bold if it needs, I'm not sure.

We've just gained some UI people so there will be a proper redesign of things soon but in the meantime I think if we simplify this one it will just blend in very nicely with the existing style of the cards and hold better until we have to rework the overall image of kindly

File: components/ItemCard.tsx [hunk 2]
```diff
@@ -11,6 +11,7 @@ type ItemCardPropType = {
   postcode?: string;
   postable?: boolean;
   itemId?: number;
+  reserved?: boolean;
```
Comment (camelPhonso) [inline components/ItemCard.tsx:14]: I really appreciate you going with the pre-set approach to the props but I can't for the life of me think why these were all set as optional props 😅 

I tried removing that and just navigating through the app for a little and nothing caught fire so can you make them all standard props instead please?

File: components/ItemCard.tsx [hunk 3]
```diff
@@ -21,11 +22,20 @@ const ItemCard: React.FC<ItemCardPropType> = ({
...
   return (
     <div className='card'>
       <Link href={`/item/${itemId}`} className=''>
-        <h2 className='p-4  font-semibold'>{item_name}</h2>
+        <div className='flex flex-row justify-between align-middle'>
+          <h2 className='p-4  font-semibold'>{item_name}</h2>
+          {reserved && (
+            <span className='place-self-center rounded-full bg-primaryOrange p-2'>
+              Reserved
+            </span>
```
Comment (camelPhonso) [inline components/ItemCard.tsx:36]: If we're doing it twice already what about just packaging it up into a class in our `globals.css`?

With our new milestone for browsing I can imagine we'll rework and reuse this little flag a few times an having it neatly referenced in one spot will make it easier.

File: components/ItemCard.stories.ts [hunk 4]
```diff
@@ -19,5 +19,6 @@ export const ItemCardDefault: Story = {
     postcode: 'E12',
     postable: true,
     itemId: 2,
+    reserved: true,
```
Comment (camelPhonso) [inline components/ItemCard.stories.ts:22]: ✨  Yes! Adding to the component library !!

Let's push our use of stories though and make it into it's own example.

If you look at the `ConversationCard` stories you'll see it has a few different stories to show all the different states it might have in the app. Can you revert the default ItemCard to not being reserved and then add a `ItemCardReserved` story?

The other addition that will help loads is to add an interaction test that verifies the card with the `reserved` value is in fact showing the "reserved" tag in the UI. You can see how this is done by looking at the `play` function in the `ConversationCard` stories.

For this case, you will only need the `play` function in the new story export, not the `meta` object.

**Review by camelPhonso — CHANGES_REQUESTED** [review]
This is top stuff!! Your changes were really focused and elegant, thanks!

I've asked for a few additions that will help us with maintainability down the road but apart from that everything looks capital 👌

File: app/(dashboard)/item/[id]/page.tsx (hunk 1 above)
Comment (mickeymarse) [reply app/(dashboard)/item/[id]/page.tsx:62]: I sure can, no problem. 😃

File: components/ItemCard.tsx (hunk 2 above)
Comment (mickeymarse) [reply components/ItemCard.tsx:14]: I was confused by this as well, and they were actually causing an issue when debugging the code.
I believe it is actually better for them not to be optional, so very happy to change that.

File: components/ItemCard.tsx (hunk 3 above)
Comment (mickeymarse) [reply components/ItemCard.tsx:36]: Should I make the whole **Reserved** label as a component itself? Or you prefer to have just the classes?

File: components/ItemCard.stories.ts (hunk 4 above)
Comment (mickeymarse) [reply components/ItemCard.stories.ts:22]: I never really played around with Storybook so more than happy to do this.
It sounds pretty straightforward, but I will get back to you in case I have issues with anything.

File: components/ItemCard.tsx (hunk 3 above)
Comment (camelPhonso) [reply components/ItemCard.tsx:36]: You know what, I spent a little bit thinking about this as well. I was thinking making a component out of it in case we want to show it in the `CurrentConversation` for example, but I think the application might change enough that we'd not really re-use the same component and since it's not doing any data displaying or anything it's probably enough to have it as a class we can apply to any `<p>` at will.

If you think there's a case for a full component I won't oppose it either, but it's probably a justifiable iteration right now to stick to a css class

File: components/ItemCard.stories.ts (hunk 4 above)
Comment (camelPhonso) [reply components/ItemCard.stories.ts:22]: There are a few examples in the code base already of how we're using it and their documentation is pretty good, but in case of any doubt I'm happy to lend a hand 👌

**Comment by mickeymarse** [comment]
Implemented tests and refactored code as requested by @camelPhonso .

File: components/ItemCard.stories.tsx
Comment (camelPhonso) [inline components/ItemCard.stories.tsx:1]: `.stories` files don't need to be tsx unless we are using components in the decorators.

Honestly it's fine to declare them either way (`.ts` or `.tsx`) but since this one was already created as a `.ts` it's better to not replace it entirely in a commit just as a best practice to protect our versioning history.

Can you please revert to the original name so that the changes in your pr register just the exact lines you're editing?

**Review by camelPhonso — CHANGES_REQUESTED** [review]
You get a gif for having left a `console.log` behind 😬 

After these tiny cleanups I think you're ready to merge though 👍

File: components/ItemCard.stories.tsx
Comment (mickeymarse) [reply components/ItemCard.stories.tsx:1]: Done. Sorry about that.

File: package.json [hunk 5]
```diff
@@ -84,5 +84,6 @@
       "prettier --write",
       "eslint --fix"
     ]
-  }
+  },
+  "packageManager": "yarn@1.22.22+sha1.ac34549e6aa8e7ead463a7407e1c7390f61a6610"
```
Comment (camelPhonso) [inline package.json:88]: 😨 let's just remove this one. everything else is perfect now

**Review by camelPhonso — CHANGES_REQUESTED** [review]

File: package.json (hunk 5 above)
Comment (mickeymarse) [reply package.json]: Damn, didn't realize it came back.
I removed it now.

**Review by camelPhonso — APPROVED** [review]
lovely jobely!

Congrats on your first PR merge ✨
