### PR TITLE
#248/notification for conversation updates

### LINKED ISSUE #248: Display notifications in Header for conversation updates
# Expected Behaviour

Users should see a clear notification that there are new updates to existing conversations when they are navigating other areas of Kindly.

The notification marker currently being displayed in `ConversationCard.tsx` should be reproduced for the button in `Header.tsx` that navigates to the `/conversations` route.

This is an example of the expected behaviour, created in Figma

Screenshot 2024-06-10 at 11 52 59

# Current Behaviour

Right now users will not be notified about any changes in their conversations until they navigate into the `/conversations` route.

## Steps to Reproduce

1. Run your local environment
2. Create a new conversation by sending a message about one of your uploaded items from a second account
3. There should be a conversation with a notification dot in your `/conversations` page
4. Return to the homepage and there will be no indication that your conversations need reviewing

### PR DESCRIPTION
**Pull request by Edga380**
# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review on my code
- [x] I have made corresponding changes to the documentation (if any were needed)
- [x] My changes generate no new warnings or errors
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and previously existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

# Description

**Closes #248** 
Notifies user if they have new conversation or message.

### Files changed

**DesktopNav.tsx/MobileNavbar.tsx**
- `useEffect` is being used to get user session, from this data we extract `userId` and set `useState`.

- `useEffect` is being used to check if the `pathname` variable is equal to path `/conversations` if  yes we set `notification` variable to `false`, because we don't want to show active notification if we are in that specific page.

- `useEffect` is being used to retrieve unread user conversations on initial opening of the website. Before doing that we check if `userId` variable is set if not we `return` and do not run the function to get the unread conversations. This `useEffect` reruns when `userId` is set. After checking the database for unread conversations we retrieve an array of unread conversation then check if array is empty or not by checking it's `length` if `length > 0` then we set notification to `true`.

- `useEffect` is being used to create a `supabase.channel` and listen to `user_conversations` table in the database for changes. This `useEffect` is being triggered by variables `trigger`, `pathname` and `userId` so that we definitely rerun this `useEffect` because if we do not the real time database listening will stop and will no longer get notifications.

- Lower in the code there is notification styling and it's being triggered if variable `notification` is `true`
```
{notification && (
  <div
    className='absolute right-4 top-3 z-50 h-3 w-3 rounded-full border-2 
      border-green-700 bg-[#54BB89] shadow-lg outline-4 outline-black'
  ></div>
)}
```
**NavigationLinkContainer.tsx**
- `relative` position was added so that we could position notification dot on top of the icon with `absolute` position.
```
className={`relative flex flex-col items-center justify-center...
```

### Files Added
**selectUserUnreadMessages.ts**
- With the function `selectUserUnreadConversations` in this file we check `user_conversations` table in the database using `userId` variable and we specifically check if any of the conversations have `has_unread_messages` field set to `true` after that we return an array.

### UI changes
- **Desktop version**
Screenshot from 2024-07-03 13-30-44

- **Mobile version**
Screenshot from 2024-07-03 13-30-11

### Changes to Documentation

None

# Tests

None

### CODE REVIEW

**Review by camelPhonso — CHANGES_REQUESTED** [review]
Top stuff dude 👌 

Requested a few bits but this is another killer PR! If only you didn't love closing tags so much 💔

File: components/navigation/DesktopNav.tsx [hunk 1]
```diff
@@ -9,8 +11,91 @@ import SearchRouteIcon from '../icons/navigation/SearchRouteIcon';
...
+      }
+    };
+    getUserSession();
+  }, []);
+
+  useEffect(() => {
+    if (pathname === '/conversations') {
+      setNotification(false);
+    }
+  }, [pathname]);
```
[the remark this answers is not in the document]
Comment (Edga380) [reply components/navigation/DesktopNav.tsx:43]: Yes you are correct we don't need this `useEffect` I did like you said to store a boolean and it's works just fine:
```
const isConversationsRoute = pathname === '/conversations';
```
and then this:
```
{notification && !isConversationsRoute && (
          <div...
```

File: components/navigation/DesktopNav.tsx [hunk 2]
```diff
@@ -9,8 +11,91 @@ import SearchRouteIcon from '../icons/navigation/SearchRouteIcon';
...
+      try {
+        const { data: userData } = await supabase.auth.getSession();
+        if (userData.session?.user.id) {
+          setUserId(userData.session?.user.id);
+        }
+      } catch (error) {
+        console.error('Error getting user session: ', error);
+      }
+    };
+    getUserSession();
```
[the remark this answers is not in the document]
Comment (Edga380) [reply components/navigation/DesktopNav.tsx:36]: So the code for this `useEffect` looks like this: 
```
  useEffect(() => {
    const getUserId = async () => {
      const data = await selectLoggedUserId();
      if (data) {
        setUserId(data);
      } else {
        console.error('Failed to fetch user Id');
      }
    };
    getUserId();
  }, []);
```
I removed curly brackets on `data` variable because I assume we only want to receive `userId` and nothing else from `selectLoggedUserId` function and I still want to log some kind of `error` if their is no data fetched in `selectLoggedUserId` function there is error handling too.

```
import { createClientComponentClient } from '@supabase/auth-helpers-nextjs';

export default async function selectLoggedUserId() {
  const supabase = createClientComponentClient();
  try {
    const { data, error } = await supabase.auth.getSession();

    if (error) throw error;

    return data.session?.user.id;
  } catch (error) {
    console.error('Error getting user session: ', error);
  }
}
```

File: components/navigation/DesktopNav.tsx [hunk 3]
```diff
@@ -52,6 +137,12 @@ const DesktopNav = () => {
       >
         <MessageRouteIcon width={38} height={38} pathName={pathname} />
         Message
+        {notification && (
+          <div
+            className='absolute right-4 top-3 z-50 h-3 w-3 rounded-full border-2 
+              border-green-700 bg-[#54BB89] shadow-lg outline-4 outline-black'
+          ></div>
```
[the remark this answers is not in the document]
Comment (Edga380) [reply components/navigation/DesktopNav.tsx:144]: Apologies for the closing tag :disappointed: 
I can do that but the only thing that is different between the dots is it's sizing, but I can change it with tailwind on the element itself.

File: components/navigation/DesktopNav.tsx (hunk 1 above)
[the remark this answers is not in the document]
Comment (Edga380) [reply components/navigation/DesktopNav.tsx:43]: Edit:
Actually I just realised that we lost the logic to `setNotification` back to `false` so I think we have to use this `useEffect` to do so.

File: components/navigation/DesktopNav.tsx (hunk 3 above)
[the remark this answers is not in the document]
Comment (Edga380) [reply components/navigation/DesktopNav.tsx:144]: So I found what was the issue with absolute I didn't import the `messaging-styles.css` after doing that it works fine. Also because I didn't do that the dot was not appearing in other pages unless you visited conversations page so made myself confused why the code wasn't working anymore silly me :sweat_smile:

File: components/navigation/DesktopNav.tsx [hunk 4]
```diff
@@ -1,58 +1,57 @@
...
+    const getUserId = async () => {
+      const data = await selectLoggedUserId();
+      if (data) {
+        setUserId(data);
+      } else {
+        console.error('Failed to fetch user Id');
       }
     };
-    getUserSession();
+    getUserId();
```
Comment (camelPhonso) [inline components/navigation/DesktopNav.tsx:33]: ah, nice 👌 cool little refactor

File: components/navigation/DesktopNav.tsx [hunk 5]
```diff
@@ -95,7 +92,7 @@ const DesktopNav = () => {
     return () => {
       supabase.removeChannel(channel);
     };
-  }, [trigger, pathname, userId]);
+  }, [notification, pathname, userId]);
```
Comment (camelPhonso) [inline components/navigation/DesktopNav.tsx:95]: I didn't spot this before but please adjust this name to reflect a boolean - `hasNotifications` or something

**Review by camelPhonso — CHANGES_REQUESTED** [review]

File: supabase/utils/selectLoggedUserId.ts [hunk 6]
```diff
@@ -0,0 +1,14 @@
+import { createClientComponentClient } from '@supabase/auth-helpers-nextjs';
+
+export default async function selectLoggedUserId() {
+  const supabase = createClientComponentClient();
```
[the remark this answers is not in the document]
Comment (Edga380) [reply supabase/utils/selectLoggedUserId.ts:4]: Hey @camelPhonso I have been working on this and using `newClient` does not work for some reason I do not get any data, but if I use `createClientComponentClient` it works perfectly. Not sure if I am using it incorrectly.

```
import newClient from './newClient';

export default async function selectLoggedUserId() {
  const supabase = newClient();
  try {
    const { data, error } = await supabase.auth.getSession();

    if (error) throw error;

    return data.session?.user.id;
  } catch (error) {
    console.error('Error getting user session: ', error);
  }
}
```

[the remark this answers is not in the document]
Comment (Edga380) [reply supabase/utils/selectLoggedUserId.ts]: Instead of `newClient` we use `newServerClient` and instead of `getSession()` we use `getUser()`

File: components/navigation/DesktopNav.tsx [hunk 7]
```diff
@@ -1,16 +1,105 @@
...
+    const getUserId = async () => {
+      try {
+        const data = await selectLoggedUserId();
+        if (data) {
+          setUserId(data);
+        } else {
+          console.error('Failed to fetch user Id');
+        }
+      } catch (error) {
+        console.error('Error fetching user Id:', error);
```
Comment (camelPhonso) [inline components/navigation/DesktopNav.tsx:34]: This seems redundant  - your `selectLoggedUserId` function already throws an error so you'll get it in the catch - just throw it again

File: components/navigation/MobileNavbar.tsx [hunk 8]
```diff
@@ -8,9 +7,99 @@ import SearchRouteIcon from '../icons/navigation/SearchRouteIcon';
...
+        },
+        (payload) => {
+          if (payload.new.has_unread_messages) {
+            if (pathname !== '/conversations') {
+              setHasNotification(true);
+            }
+          }
+        }
+      )
+      .subscribe();
```
Comment (camelPhonso) [inline components/navigation/MobileNavbar.tsx:97]: Let's package this away shall we? 📦 

could probably go into `supabase/channels/notificationsWatcher.ts` ??

File: app/styles/messaging-styles.css [hunk 9]
```diff
@@ -10,6 +10,18 @@
...
+  position: absolute;
+  height: 1rem;
+  width: 1rem;
+  border-radius: 50%;
+  border-width: 2px;
+  border-color: #2f855a;
+  background-color: #54bb89;
+  box-shadow: 0 0 1px black;
+  z-index: 50;
+}
```
Comment (camelPhonso) [inline app/styles/messaging-styles.css:24]: Now that we have a component this seems out of place 😅 

But you did some creative thinking with the new props so why not declare this is the `NotificationDot.tsx` file and interpolate the passed prop values straight into it?

Probably remove the option for sizing though - I think the designers will want to keep that uniform, but we might well need to adjust the position when we place it in different areas so keep that one :)

**Review by camelPhonso — CHANGES_REQUESTED** [review]
Nice stuff 👌 I really liked your edit to make the notification dot easily adjustable.

There's a chance to do some extra clean up but apart from that it's looking good.

File: components/navigation/MobileNavbar.tsx [hunk 10]
```diff
@@ -8,9 +7,57 @@ import SearchRouteIcon from '../icons/navigation/SearchRouteIcon';
...
+      } catch (error) {
+        console.error('Error fetching user Id:', error);
+      }
+    };
+    getUserId();
+  }, []);
+
+  useEffect(() => {
+    const getUnreadConversations = async () => {
+      if (!userId) return;
```
Comment (camelPhonso) [inline components/navigation/MobileNavbar.tsx:38]:
```ts
if (!userId || pathname === '/conversations') {
  setHasNotification(false)
  return
}
```

we can just have an early return and avoid a database call entirely if we are already on './conversations'

File: components/navigation/MobileNavbar.tsx [hunk 11]
```diff
@@ -8,9 +7,57 @@ import SearchRouteIcon from '../icons/navigation/SearchRouteIcon';
...
+
+  useEffect(() => {
+    if (pathname === '/conversations') {
+      setHasNotification(false);
+    }
+  }, [pathname]);
+
+  useEffect(() => {
+    notificationWatcher(userId, pathname, setHasNotification);
+  }, [hasNotification, pathname, userId]);
```
Comment (camelPhonso) [inline components/navigation/MobileNavbar.tsx:60]: we can maybe get rid of that first `useEffect` by sticking the pathname evaluation into the second one ? (I haven't tested that idea 😅 )

File: supabase/utils/selectLoggedUserId.ts [hunk 12]
```diff
@@ -0,0 +1,16 @@
...
+export default async function selectLoggedUserId() {
+  const supabase = newServerClient();
+  try {
+    const { data, error } = await supabase.auth.getUser();
+
+    if (error) throw error;
+
+    return data.user.id;
+  } catch (error) {
+    console.error('Error getting user session: ', error);
```
Comment (camelPhonso) [inline supabase/utils/selectLoggedUserId.ts:14]: throw your error here again after logging or it won't be caught in the client side when we call this function

**Review by camelPhonso — CHANGES_REQUESTED** [review]
good stuff!

I think we might be able to thin out the useEffects in this one and touch up the error handling slightly though

File: components/navigation/MobileNavbar.tsx (hunk 10 above)
Comment (Edga380) [reply components/navigation/MobileNavbar.tsx:38]: Yes this works fine just had to add `pathname` to rerun the `useEffect`

File: components/navigation/MobileNavbar.tsx (hunk 11 above)
Comment (Edga380) [reply components/navigation/MobileNavbar.tsx:60]: Yay one less `useEffect` good thinking :+1:

**Review by camelPhonso — APPROVED** [review]
🤩 nice one!

Thanks for the quick turnaround on the requested changes. 

Another nice merge out of the way :)
