### PR TITLE
#341: Default profile image in ConversationCard component

### LINKED ISSUE #341: Default image display for profile picture in ConversationCards
### Description of the Bug

When a user's profile picture can not be retrieved the display of the `ConversationCard.tsx` should show the default image in the codebase. This behaviour is seen when there is no image provided and should be the same if the image cannot be displayed.

### What should happen instead

Right now in our seed data the images being referenced are not available in the development buckets so the cards show the alt description instead and the sizing of the profile picture is altered.
366962472-28dc0a57-0c7b-4b02-8bfe-a7ae97262949

### Steps to reproduce this bug

1. log in as one of the test users 
2. visit `/conversations`

### What could we do to solve this bug?

Currently the code in `ConversationCard.tsx` will evaluate if there is an image url available and if not it will display a default image. We should default to the same if there image is referenced but cannot be displayed or at the very least we should maintain the size and styling of the profile picture display even if we can only see the alt description for it

### Assignment

This issue is free for anyone to take

### PR DESCRIPTION
**Pull request by AnyaVeselova**
# Description

**Closes #341**  

This pull request creates a function **handleError** which sets the imgSrc state to the default placeholder image when the src fails to load. This functionality is handled with the usage of onError event in the next Image component.

### Files changed

ConversationCard

### UI changes

Screenshot from 2024-09-21 23-08-50

### CODE REVIEW

**Review by camelPhonso — CHANGES_REQUESTED** [review]
Your solution looks really elegant - really love how it leans up the code as well 👌 

Just watch out that this PR is bringing code from your previous issue along. Please remove those changes from this branch so we can keep updates separated.

**Comment by AnyaVeselova** [comment]
How do I do this? 🤔

**Comment by ShaughnAnderson94** [comment]
> How do I do this? 🤔

hard to know exactly what caused it but the most common thing is that uncommitted changes follow you when you switch branches or you are not going into dev before making the new branch so its based off your current branch which might be a different one

**Comment by AnyaVeselova** [comment]
Thank you for trying to help with my daily git struggles, @ShaughnAnderson94 ! Is it ok after I force-pushed the branch? I think those ghosts are gone now.

**Review by camelPhonso — CHANGES_REQUESTED** [review]
This is a really lean and elegant fix, I love it !

I'm requesting changes but because I can see an improvement we could make on the UI.

Currently one of the images in our seed data shows in a different shape to the rest. I suspect this is due to that card being slightly more crowded with information, but we should guarantee that the profile picture display stays consistent.

Can you have a go at the css on this one?
Screenshot 2024-09-28 at 19 14 32

**Review by camelPhonso — APPROVED** [review]
Brilliant stuff! Thanks Anna 🙌

**Comment by camelPhonso** [comment]
> Brilliant stuff! Thanks Anna 🙌

Oh no, I didn't notice there's a conflict in this file 🤦 

Can you merge the latest from dev and solve this conflict? We'll merge it in once that's cleared

File: components/messaging/ConversationCard.tsx [hunk 1]
```diff
@@ -49,27 +53,26 @@ const ConversationCard: React.FC<ConversationCardProps> = ({
...
-            alt={partnerUsername}
-            sizes='(max-width: 640px) 50px, (max-width: 768px) 75px, 100px'
-          />
+
+        ) && (
+          <div
+            className='relative left-12 z-50 h-4 w-4 rounded-full 
+              border-2 border-green-700 bg-[#54BB89] shadow-lg outline-4 outline-black'
+          ></div>
         )}
```
Comment (camelPhonso) [inline components/messaging/ConversationCard.tsx:65]: Thanks Anna, just one thing on these lines - it looks like we're losing the 'notification-dot' class here to instead declare the same styling with tailwind inline. We should stick to calling the globally defined class because this is used in several components and needs to be easily edited in future, so I'm making here an inline commit suggestion to revert this change

```suggestion
        ) && <div className='notification-dot' /> )}
```

**Review by camelPhonso — CHANGES_REQUESTED** [review]

File: components/messaging/ConversationCard.tsx (hunk 1 above)
Comment (AnyaVeselova) [reply components/messaging/ConversationCard.tsx]: sorry, I tried to commit the suggestion and it didn't go through. I'll try one more time

**Review by camelPhonso — APPROVED** [review]
